services:
  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"

  exchange-service:
    build: ./exchange-service
    container_name: exchange-service
    ports:
      - "8300:8300"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-service

  audit-service:
    build: ./audit-service
    container_name: audit-service
    ports:
      - "8200:8200"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-service

  currency-service:
    build: ./currency-service
    container_name: currency-service
    ports:
      - "8100:8100"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - eureka-service
      - exchange-service
